# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(293, 153)
        MainWindow.setStyleSheet("background-color: #29292E;\n"
"color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_red = QtWidgets.QPushButton(self.centralwidget)
        self.button_red.setGeometry(QtCore.QRect(20, 30, 31, 31))
        self.button_red.setStyleSheet("border-radius: 10px; \n"
"background-color: red;\n"
"border: 1px solid red;")
        self.button_red.setText("")
        self.button_red.setObjectName("button_red")
        self.button_yellow = QtWidgets.QPushButton(self.centralwidget)
        self.button_yellow.setGeometry(QtCore.QRect(60, 30, 31, 31))
        self.button_yellow.setStyleSheet("border-radius: 10px; \n"
"background-color: yellow;\n"
"border: 1px solid rgb(255, 255, 0);")
        self.button_yellow.setText("")
        self.button_yellow.setObjectName("button_yellow")
        self.button_green = QtWidgets.QPushButton(self.centralwidget)
        self.button_green.setGeometry(QtCore.QRect(100, 30, 31, 31))
        self.button_green.setStyleSheet("border-radius: 10px; \n"
"background-color: green;\n"
"border: 1px solid rgb(0, 159, 0);")
        self.button_green.setText("")
        self.button_green.setObjectName("button_green")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 131, 71))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 10, 131, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(9, 26, 108, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.status_message = QtWidgets.QLabel(self.centralwidget)
        self.status_message.setGeometry(QtCore.QRect(50, 130, 161, 16))
        self.status_message.setObjectName("status_message")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 90, 131, 17))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 130, 35, 16))
        self.label.setObjectName("label")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(213, 126, 75, 23))
        self.quitButton.setStyleSheet("background-color: rgb(255, 83, 83);\n"
"border-radius: 10px;")
        self.quitButton.setObjectName("quitButton")
        self.groupBox.raise_()
        self.button_red.raise_()
        self.button_yellow.raise_()
        self.button_green.raise_()
        self.groupBox_2.raise_()
        self.status_message.raise_()
        self.checkBox.raise_()
        self.label.raise_()
        self.quitButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automação com Arduino"))
        self.groupBox.setTitle(_translate("MainWindow", "Lâmpadas"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Leitura do sensor"))
        self.status_message.setText(_translate("MainWindow", "Aguardando conexão"))
        self.checkBox.setText(_translate("MainWindow", "Comando de voz"))
        self.label.setText(_translate("MainWindow", "Status:"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
